import React from 'react';

const Section = ({ title, children }: { title: string, children?: React.ReactNode }) => (
  <section>
    <h2 className="text-xl font-bold text-slate-800 dark:text-white mb-3">{title}</h2>
    <div className="text-slate-600 dark:text-slate-300 leading-relaxed">
      {children}
    </div>
  </section>
);

export const TermsPage: React.FC = () => {
  return (
    <div className="p-6 md:p-12 overflow-y-auto h-full max-w-4xl mx-auto font-sans text-slate-700 dark:text-slate-300">
      <h1 className="text-4xl font-bold text-slate-800 dark:text-white mb-8">Terms & Conditions</h1>
      <div className="bg-white dark:bg-navy-800 p-8 rounded-3xl shadow-sm border border-slate-100 dark:border-navy-700 space-y-8">
        
        {/* Intro */}
        <p className="italic opacity-80 border-l-4 border-lavender-400 pl-4">
          By accessing or using Sukoon AI Therapist, you acknowledge and agree to these terms. If you do not agree, you must discontinue using the service immediately.
        </p>

        <Section title="1. Purpose of Sukoon AI Therapist">
          <p>Sukoon AI Therapist is an AI-powered emotional wellness companion designed to provide supportive conversation, reflective guidance, mindfulness suggestions, mood tracking, and general emotional insights. It aims to create a safe space where users can:</p>
          <ul className="list-disc ml-6 mt-2 space-y-1">
            <li>Share their thoughts and feelings</li>
            <li>Explore personal emotions</li>
            <li>Reflect on daily experiences</li>
            <li>Receive gentle, non-clinical support</li>
            <li>Build healthier emotional habits</li>
          </ul>
          <p className="mt-2 font-semibold text-rose-500">Sukoon AI is not a substitute for licensed therapy, clinical treatment, psychiatric evaluation, or any form of professional counseling.</p>
        </Section>

        <Section title="2. No Professional Medical or Psychological Advice">
          <p>Sukoon AI Therapist is not a licensed therapist, psychologist, psychiatrist, counselor, or medical professional. It does not provide medical, psychological, clinical, or diagnostic advice.</p>
          <p className="mt-2">All insights and reflections generated by the AI are general emotional guidance only. Users must understand that AI-generated responses may not always be correct, complete, or appropriate for serious emotional conditions.</p>
        </Section>

        <Section title="3. Emergency & Crisis Situations">
          <p className="font-bold text-rose-600">Sukoon AI is not designed to respond to emergencies or high-risk mental health situations.</p>
          <p className="mt-2">If you experience suicidal thoughts, self-harm urges, panic attacks, or severe distress, do NOT rely on Sukoon AI. Immediately contact local emergency services, suicide prevention hotlines, or a trusted professional.</p>
        </Section>

        <Section title="4. User Responsibility">
          <p>By using Sukoon AI, you agree that you are solely responsible for your decisions, actions, and interpretations of AI-generated content. You will not treat AI responses as medical advice and will seek professional help for serious concerns.</p>
        </Section>

        <Section title="5. Data & Privacy">
          <p>Your chat history, mood logs, and journals belong to you. We do not sell user data. While we strive for privacy, please note that this is a prototype system. Admin users access aggregated analytics but not private conversation contents.</p>
        </Section>

        <Section title="6. Limitations of the AI System">
          <p>Like all AI systems, Sukoon AI may misinterpret context, provide incomplete answers, or fail to detect high-risk behavior. Use discretion when engaging with the system.</p>
        </Section>

        <Section title="7. Emotional Safety & Ethical Use">
          <p>Users must not use Sukoon AI to seek clinical diagnoses, replace professional therapy, or engage in harmful interactions. The system is designed for emotional safety but cannot replace human judgment.</p>
        </Section>

        <Section title="8. Eligibility">
          <p>You must be at least 16 years old to use this service. Each user is responsible for maintaining the confidentiality of their account credentials.</p>
        </Section>

        <Section title="9. Acceptance of Terms">
          <p>By using this app, you accept full responsibility for your well-being. You agree not to hold Sukoon AI, its creators, or developers liable for outcomes based on AI-generated content.</p>
        </Section>

        <Section title="10. Changes to Terms">
          <p>Sukoon AI reserves the right to update these terms at any time to enhance safety and compliance. Continued use indicates acceptance.</p>
        </Section>

        <div className="border-t border-slate-200 dark:border-navy-600 pt-8">
            <h2 className="text-xl font-bold text-slate-800 dark:text-white mb-4">11. Known System Issues & Prototype Disclaimer</h2>
            <div className="bg-slate-50 dark:bg-navy-900 p-6 rounded-xl text-sm space-y-4">
                <p><strong>A. User Login Persistence:</strong> Some users may experience session timeouts or require re-login upon refreshing the browser. This is a known limitation of the current prototype environment.</p>
                <p><strong>B. Data Persistence:</strong> As this version utilizes browser-based storage (LocalStorage) for demonstration purposes, clearing your browser cache or switching devices will result in data loss. We are working on a dedicated cloud backend (Supabase/Firebase) to resolve this.</p>
                <p><strong>C. Workaround:</strong> Please manually back up important journal entries. Do not use this prototype for critical long-term therapeutic records until the full database release.</p>
                <p><strong>D. Disclaimer:</strong> These technical limitations do not affect your immediate emotional safety during a session, but affect the system's ability to "remember" you long-term across different devices.</p>
            </div>
        </div>

      </div>
    </div>
  );
};